### ISSUE TITLE
Omit private IPs from VMI interface status for VMs with masquerade binding

### ISSUE THREAD

**Issue by frenzyfriday** [kubevirt/kubevirt#16421]
**What happened**:
If pod IP does not exist in VMI interface status, the IP from guest agent (if present) is written to the status. 
So in a dual stack or single IPv4 stack environment if pod IP does not exist and internal IP addresses are still configured on the guest VM (though dhcp/ipam etc maybe), they are shown on the interface status even though they are not reachable.

**What you expected to happen**:
In dual stack or single IPv4 stack environments only the pod IP should appear on the interface status.

**How to reproduce it (as minimally and precisely as possible)**:
Create a VM with masquerade binding without a pod IP in a single ipv4 or dual stack environment.
Configure an IPv4 private IP manually or through cloudinit on the guest VM.
Check the VMI interface status for this IP.

**Additional context**:
The [e2e test](https://github.com/kubevirt/kubevirt/blob/5bcc0285422e0cb7f2918bc9907d676a5f0b342f/tests/network/networkpolicy.go#L123) that verifies connectivity between 2 masquerage VMs does not catch this as of now. The IPs configured on the server and client VMs [through cloudinit](https://github.com/kubevirt/kubevirt/blob/988472e0fef5c66e0ee5df43a07f0fc231a4b2c3/tests/libnet/cloudinit/cloudinit.go#L183) are the same. So if the client VM pings the server IP, and even if this server IP is not reachable, it essentially pings itself and passes.

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by orelmisan** [comment]
Hey @frenzyfriday, is this resolved by #16242?
/remove-lifecycle stale

**Comment by danudey** [comment]
> Hey [@frenzyfriday](https://github.com/frenzyfriday), is this resolved by [#16242](https://github.com/kubevirt/kubevirt/pull/16242)? /remove-lifecycle stale

Unfortunately this doesn't solve it because this is a [unique-local address](https://en.wikipedia.org/wiki/Unique_local_address) and not a link-local address.

From what I'm able to tell from the code, the best solution is to:

1. Get the list of masquerade prefixes (i.e. the internal non-routable CIDRs on the VM) for each network
2. Remove any addresses from consideration which fall within the masquerade prefix

I have a patch to do this which I'm in the process of testing against a new cluster; if it works as expected, I'll open a PR for this issue. This is core to us finishing our OpenShift Container Platform certification, which is the context in which I'm working, though I'm not sure if this would cause any other issues elsewhere in Kubevirt yet (i.e. expectations unmet or edge cases unconsidered).

**Comment by frenzyfriday** [comment]
I think I filed the issue initially to remove the LLA IPs in case of masquerade interface. 
Do we have a real scenario where the pod IP can be unset in a VM with masquerade interface?

**Comment by EdDev** [comment]
> I think I filed the issue initially to remove the LLA IPs in case of masquerade interface. Do we have a real scenario where the pod IP can be unset in a VM with masquerade interface?

The scenario described on the issue seems clear to me:

> How to reproduce it (as minimally and precisely as possible):
> Create a VM with masquerade binding without a pod IP in a single ipv4/6 or dual stack environment.
> Configure an IPv4 private IP manually or through cloudinit on the guest VM.
> Check the VMI interface status for this IP.

Which part is not clear?

**Comment by frenzyfriday** [comment]
> Create a VM with masquerade binding without a pod IP

What is the spec in this case?
```
          interfaces:
          - masquerade: {}
            name: default
...
      networks:
      - name: default
        pod: {}
```

I mean how do I ensure it does not get a pod IP if the iface is masquerade?
