### ISSUE TITLE
Failed to connect socket to '/var/run/libvirt/libvirt-sock

### ISSUE THREAD

**Issue by Mohitsharma44** [kubevirt/kubevirt#5069]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
`virt-launcher` pod keeps restarting. Logs mentioned below

**What you expected to happen**:
vm would launch

**How to reproduce it (as minimally and precisely as possible)**:
Followed the quick start guide for setting up kubevirt on `microk8s`. Specific steps to reproduce:
```
export VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | grep tag_name | grep -v -- '-rc' | head -1 | awk -F': ' '{print $2}' | sed 's/,//' | xargs)
echo $VERSION
kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/kubevirt-operator.yaml
kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/kubevirt-cr.yaml
kubectl get all -n kubevirt
kubectl apply -f https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/vm.yaml
kubectl virt start testvm
```
> Outputs mentioned in the comment

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 
  ```
  Client Version: version.Info{GitVersion:"v0.38.1", GitCommit:"8c3ba52f8ce7cbb55c29919e9c263617716aa054", 
  GitTreeState:"clean", BuildDate:"2021-02-08T20:04:23Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{GitVersion:"v0.38.1-dirty", GitCommit:"8c3ba52f8ce7cbb55c29919e9c263617716aa054", 
  GitTreeState:"dirty", BuildDate:"2021-02-08T20:30:01Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Kubernetes version (use `kubectl version`):
  ```
  Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.2-35+dd776c00dc6dae", 
  GitCommit:"dd776c00dc6daeeaac288589c545a4d253718f5d", GitTreeState:"clean", BuildDate:"2021-02-12T11:13:34Z", 
  GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.2-35+dd776c00dc6dae", 
  GitCommit:"dd776c00dc6daeeaac288589c545a4d253718f5d", GitTreeState:"clean", BuildDate:"2021-02-12T11:04:51Z", 
  GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
  ```
- VM or VMI specifications: https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/vm.yaml
- Cloud provider or hardware configuration:
  ```
  Virtual Machine running on vSphere 7.0.1.
  nested virtualization enabled.
  I/O MMU enabled.
  ```
- OS (e.g. from /etc/os-release):
  ```
  NAME="Ubuntu"
  VERSION="20.04.1 LTS (Focal Fossa)"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu 20.04.1 LTS"
  VERSION_ID="20.04"
  HOME_URL="https://www.ubuntu.com/"
  SUPPORT_URL="https://help.ubuntu.com/"
  BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
  PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
  VERSION_CODENAME=focal
  UBUNTU_CODENAME=focal
  ```
- Kernel (e.g. `uname -a`):
  ```
  Linux uohost-01.phoenixdc.sharmamohit.com 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
  ```
- Install tools:
- Others:
  calico CNI plugin with ip forwarding enabled.
  ```
  k describe cm calico-config -n kube-system | grep ip_forwarding
          "allow_ip_forwarding": true
  ```
-------------------------------
Logs/ Stdout:
- Logs from compute container virt-launcher pod:
  ```
  kubectl logs -f virt-launcher-testvm-49b46 -c compute
  
  {"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar 
   sockets","pos":"manager.go:68","timestamp":"2021-02-21T05:30:05.814767Z"}
  {"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority 
  and name: map[]","pos":"manager.go:71","timestamp":"2021-02-21T05:30:05.814825Z"}
  {"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: 
  qemu:///system","pos":"libvirt.go:417","timestamp":"2021-02-21T05:30:05.866380Z"}
  {"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, 
  Message='Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or 
  directory')","pos":"libvirt.go:425","timestamp":"2021-02-21T05:30:05.868031Z"}
  {"component":"virt-launcher","level":"info","msg":"libvirt version: 6.6.0, package: 13.fc32 (Unknown, 2021-01-21-11:33:00, 
  )","subcomponent":"libvirt","thread":"43","timestamp":"2021-02-21T05:30:05.883000Z"}
  {"component":"virt-launcher","level":"info","msg":"hostname: 
  testvm","subcomponent":"libvirt","thread":"43","timestamp":"2021-02-21T05:30:05.883000Z"}
  {"component":"virt-launcher","level":"error","msg":"internal error: Child process (dmidecode -q -t 0,1,2,3,4,11,17) 
  unexpected exit status 1: /dev/mem: No such file or 
  directory","pos":"virCommandWait:2741","subcomponent":"libvirt","thread":"43","timestamp":"2021-02- 
  21T05:30:05.883000Z"}
  {"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:433","timestamp":"2021- 
  02-21T05:30:06.369644Z"}
  {"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify 
  callback","pos":"client.go:432","timestamp":"2021-02-21T05:30:06.374186Z"}
  {"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:73","timestamp":"2021-02- 
  21T05:30:06.374474Z"}
  {"component":"virt-launcher","level":"info","msg":"Received signal terminated","pos":"virt- 
  launcher.go:437","timestamp":"2021-02-21T05:30:10.286996Z"}
  {"component":"virt-launcher","level":"info","msg":"stopping cmd server","pos":"server.go:448","timestamp":"2021-02- 
  21T05:30:10.287245Z"}
  {"component":"virt-launcher","level":"info","msg":"cmd server stopped","pos":"server.go:457","timestamp":"2021-02- 
  21T05:30:10.287382Z"}
  {"component":"virt-launcher","level":"info","msg":"Exiting...","pos":"virt-launcher.go:466","timestamp":"2021-02- 
  21T05:30:10.287410Z"}
  ```

**Comment by Mohitsharma44** [comment]
Exact steps and their output that were run (a couple of times in fresh Microk8s instance):

- Get latest release:
```
$ export VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | grep tag_name | grep -v -- '-rc' | head -1 | awk -F': ' '{print $2}' | sed 's/,//' | xargs)
$ echo $VERSION
v0.38.1
```

- kubevirt-operator:
```
$ kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/kubevirt-operator.yaml
namespace/kubevirt created
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/kubevirts.kubevirt.io created
priorityclass.scheduling.k8s.io/kubevirt-cluster-critical created
clusterrole.rbac.authorization.k8s.io/kubevirt.io:operator created
serviceaccount/kubevirt-operator created
role.rbac.authorization.k8s.io/kubevirt-operator created
rolebinding.rbac.authorization.k8s.io/kubevirt-operator-rolebinding created
clusterrole.rbac.authorization.k8s.io/kubevirt-operator created
clusterrolebinding.rbac.authorization.k8s.io/kubevirt-operator created
deployment.apps/virt-operator created
```

- useEmulation:
```
$ kubectl create configmap kubevirt-config -n kubevirt --from-literal debug.useEmulation=true
configmap/kubevirt-config created
```
> I've tried with and without enabling emulation

- custom resource definition:
```
$ kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/kubevirt-cr.yaml
kubevirt.kubevirt.io/kubevirt created
```

- Verify everything came up fine:
```
$ kubectl get all -n kubevirt
NAME                                   READY   STATUS    RESTARTS   AGE
pod/virt-operator-79574b7dc5-xt865     1/1     Running   0          3m40s
pod/virt-operator-79574b7dc5-tvh4v     1/1     Running   0          3m40s
pod/virt-api-555f7bb78-d79ql           1/1     Running   0          2m59s
pod/virt-api-555f7bb78-gh2sb           1/1     Running   0          2m59s
pod/virt-controller-85688dbdb6-hw5gg   1/1     Running   0          2m28s
pod/virt-controller-85688dbdb6-q5bwn   1/1     Running   0          2m28s
pod/virt-handler-85xgw                 1/1     Running   0          2m28s

NAME                                  TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/kubevirt-prometheus-metrics   ClusterIP   10.152.183.63    <none>        443/TCP   2m59s
service/virt-api                      ClusterIP   10.152.183.74    <none>        443/TCP   2m59s
service/kubevirt-operator-webhook     ClusterIP   10.152.183.154   <none>        443/TCP   2m59s

NAME                          DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/virt-handler   1         1         1       1            1           kubernetes.io/os=linux   2m28s

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/virt-operator     2/2     2            2           3m40s
deployment.apps/virt-api          2/2     2            2           2m59s
deployment.apps/virt-controller   2/2     2            2           2m28s

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/virt-operator-79574b7dc5     2         2         2       3m40s
replicaset.apps/virt-api-555f7bb78           2         2         2       2m59s
replicaset.apps/virt-controller-85688dbdb6   2         2         2       2m28s

NAME                            AGE    PHASE
kubevirt.kubevirt.io/kubevirt   3m9s   Deployed
```

- Made sure ip forwarding is enabled:
```
$ kubectl describe cm calico-config -n kube-system | grep "ip_forwarding" -A1 -B1
      "container_settings": {
          "allow_ip_forwarding": true
      },
```

- (Re-)Install virtctl via krew:
```
$ kubectl krew install virt

Updated the local copy of plugin index.
Installing plugin: virt
W0220 21:14:17.806504 1408738 install.go:160] Skipping plugin "virt", it is already installed
```

- Create VM:
```
$ kubectl apply -f https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/vm.yaml
virtualmachine.kubevirt.io/testvm created

$ kubectl get vms
NAME     AGE   VOLUME
testvm   7s

$ kubectl get vms -o yaml testvm
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubevirt.io/v1alpha3","kind":"VirtualMachine","metadata":{"annotations":{},"name":"testvm","namespace":"default"},"spec":{"running":false,"template":{"metadata":{"labels":{"kubevirt.io/domain":"testvm","kubevirt.io/size":"small"}},"spec":{"domain":{"devices":{"disks":[{"disk":{"bus":"virtio"},"name":"containerdisk"},{"disk":{"bus":"virtio"},"name":"cloudinitdisk"}],"interfaces":[{"bridge":{},"name":"default"}]},"resources":{"requests":{"memory":"64M"}}},"networks":[{"name":"default","pod":{}}],"volumes":[{"containerDisk":{"image":"kubevirt/cirros-container-disk-demo"},"name":"containerdisk"},{"cloudInitNoCloud":{"userDataBase64":"SGkuXG4="},"name":"cloudinitdisk"}]}}}}
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
  creationTimestamp: "2021-02-21T05:22:13Z"
  generation: 1
  managedFields:
  - apiVersion: kubevirt.io/v1alpha3
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:running: {}
        f:template:
          .: {}
          f:metadata:
            .: {}
            f:labels:
              .: {}
              f:kubevirt.io/domain: {}
              f:kubevirt.io/size: {}
          f:spec:
            .: {}
            f:domain:
              .: {}
              f:devices:
                .: {}
                f:disks: {}
                f:interfaces: {}
              f:resources:
                .: {}
                f:requests:
                  .: {}
                  f:memory: {}
            f:networks: {}
            f:volumes: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-02-21T05:22:13Z"
  - apiVersion: kubevirt.io/v1alpha3
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubevirt.io/latest-observed-api-version: {}
          f:kubevirt.io/storage-observed-api-version: {}
      f:status:
        .: {}
        f:volumeSnapshotStatuses: {}
    manager: virt-controller
    operation: Update
    time: "2021-02-21T05:22:13Z"
  name: testvm
  namespace: default
  resourceVersion: "3851"
  selfLink: /apis/kubevirt.io/v1/namespaces/default/virtualmachines/testvm
  uid: c36f3817-8af2-4ac5-9304-af7e987897fc
spec:
  running: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: testvm
        kubevirt.io/size: small
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - bridge: {}
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
      - containerDisk:
          image: kubevirt/cirros-container-disk-demo
        name: containerdisk
      - cloudInitNoCloud:
          userDataBase64: SGkuXG4=
        name: cloudinitdisk
status:
  volumeSnapshotStatuses:
  - enabled: false
    name: containerdisk
    reason: Volume type does not suport snapshots
  - enabled: false
    name: cloudinitdisk
    reason: Volume type does not suport snapshots
```

- Start the VM:
```
$ kubectl virt start testvm
VM testvm was scheduled to start

$ kubectl get po
NAME                         READY   STATUS        RESTARTS   AGE
virt-launcher-testvm-k54lq   0/2     Terminating   0          18s

$ k describe po virt-launcher-testvm-k54lq
Name:                      virt-launcher-testvm-k54lq
Namespace:                 default
Priority:                  0
Node:                      uohost-01.phoenixdc.sharmamohit.com/192.168.40.184
Start Time:                Sat, 20 Feb 2021 21:26:44 -0800
Labels:                    kubevirt.io=virt-launcher
                           kubevirt.io/created-by=c5ea335b-8bab-4d9c-bece-9c1ac63e7bb2
                           kubevirt.io/domain=testvm
                           kubevirt.io/size=small
Annotations:               cni.projectcalico.org/podIP: 10.1.58.138/32
                           cni.projectcalico.org/podIPs: 10.1.58.138/32
                           kubevirt.io/domain: testvm
Status:                    Terminating (lasts <invalid>)
Termination Grace Period:  60s
IP:                        10.1.58.138
IPs:
  IP:           10.1.58.138
Controlled By:  VirtualMachineInstance/testvm
Init Containers:
  container-disk-binary:
    Container ID:  containerd://6b2ca1ae212165180fc12047814d65e8579fc023f05e50b42dca6b797d62b241
    Image:         quay.io/kubevirt/virt-launcher@sha256:84123d7271da7da8c5099a329ca55c38f228cc9e1d9c572a97c9d96badeccda2
    Image ID:      quay.io/kubevirt/virt-launcher@sha256:84123d7271da7da8c5099a329ca55c38f228cc9e1d9c572a97c9d96badeccda2
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/cp
      /usr/bin/container-disk
      /init/usr/bin/container-disk
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 20 Feb 2021 21:26:48 -0800
      Finished:     Sat, 20 Feb 2021 21:26:49 -0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  40M
    Requests:
      cpu:        10m
      memory:     1M
    Environment:  <none>
    Mounts:
      /init/usr/bin from virt-bin-share-dir (rw)
  volumecontainerdisk-init:
    Container ID:  containerd://227531014bc2e7c6a65e8a47ebcb2b022c075980f27b759586e9512602fe2234
    Image:         kubevirt/cirros-container-disk-demo
    Image ID:      docker.io/kubevirt/cirros-container-disk-demo@sha256:0e5ac38b20abcc7752293425b239a147868facd62cd5030dede6da6f2fc526a1
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/container-disk
    Args:
      --no-op
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 20 Feb 2021 21:26:51 -0800
      Finished:     Sat, 20 Feb 2021 21:26:51 -0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  40M
    Requests:
      cpu:        10m
      memory:     1M
    Environment:  <none>
    Mounts:
      /usr/bin from virt-bin-share-dir (rw)
      /var/run/kubevirt-ephemeral-disks/container-disk-data/c5ea335b-8bab-4d9c-bece-9c1ac63e7bb2 from container-disks (rw)
Containers:
  compute:
    Container ID:
    Image:         quay.io/kubevirt/virt-launcher@sha256:84123d7271da7da8c5099a329ca55c38f228cc9e1d9c572a97c9d96badeccda2
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/virt-launcher
      --qemu-timeout
      5m
      --name
      testvm
      --uid
      c5ea335b-8bab-4d9c-bece-9c1ac63e7bb2
      --namespace
      default
      --kubevirt-share-dir
      /var/run/kubevirt
      --ephemeral-disk-dir
      /var/run/kubevirt-ephemeral-disks
      --container-disk-dir
      /var/run/kubevirt/container-disks
      --grace-period-seconds
      45
      --hook-sidecars
      0
      --less-pvc-space-toleration
      10
      --ovmf-path
      /usr/share/OVMF
      --use-emulation
    State:          Waiting
      Reason:       PodInitializing
    Last State:     Terminated
      Reason:       ContainerStatusUnknown
      Message:      The container could not be located when the pod was deleted.  The container used to be Running
      Exit Code:    137
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
    Ready:          False
    Restart Count:  0
    Limits:
      devices.kubevirt.io/tun:  1
    Requests:
      cpu:                      100m
      devices.kubevirt.io/tun:  1
      memory:                   242382920
    Environment:                <none>
    Mounts:
      /var/run/kubevirt-ephemeral-disks from ephemeral-disks (rw)
      /var/run/kubevirt/container-disks from container-disks (rw)
      /var/run/kubevirt/hotplug-disks from hotplug-disks (rw)
      /var/run/kubevirt/sockets from sockets (rw)
      /var/run/libvirt from libvirt-runtime (rw)
  volumecontainerdisk:
    Container ID:
    Image:         kubevirt/cirros-container-disk-demo
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/container-disk
    Args:
      --copy-path
      /var/run/kubevirt-ephemeral-disks/container-disk-data/c5ea335b-8bab-4d9c-bece-9c1ac63e7bb2/disk_0
    State:          Waiting
      Reason:       PodInitializing
    Last State:     Terminated
      Reason:       ContainerStatusUnknown
      Message:      The container could not be located when the pod was deleted.  The container used to be Running
      Exit Code:    137
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  40M
    Requests:
      cpu:        10m
      memory:     1M
    Environment:  <none>
    Mounts:
      /usr/bin from virt-bin-share-dir (rw)
      /var/run/kubevirt-ephemeral-disks/container-disk-data/c5ea335b-8bab-4d9c-bece-9c1ac63e7bb2 from container-disks (rw)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  sockets:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  virt-bin-share-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  libvirt-runtime:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  ephemeral-disks:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  container-disks:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  hotplug-disks:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  kubevirt.io/schedulable=true
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  23s   default-scheduler  Successfully assigned default/virt-launcher-testvm-k54lq to uohost-01.phoenixdc.sharmamohit.com
  Normal  Pulled     20s   kubelet            Container image "quay.io/kubevirt/virt-launcher@sha256:84123d7271da7da8c5099a329ca55c38f228cc9e1d9c572a97c9d96badeccda2" already present on machine
  Normal  Started    19s   kubelet            Started container container-disk-binary
  Normal  Created    19s   kubelet            Created container container-disk-binary
  Normal  Pulling    18s   kubelet            Pulling image "kubevirt/cirros-container-disk-demo"
  Normal  Created    16s   kubelet            Created container volumecontainerdisk-init
  Normal  Pulled     16s   kubelet            Successfully pulled image "kubevirt/cirros-container-disk-demo" in 1.630317096s
  Normal  Started    16s   kubelet            Started container volumecontainerdisk-init
  Normal  Created    15s   kubelet            Created container compute
  Normal  Pulled     15s   kubelet            Container image "quay.io/kubevirt/virt-launcher@sha256:84123d7271da7da8c5099a329ca55c38f228cc9e1d9c572a97c9d96badeccda2" already present on machine
  Normal  Started    14s   kubelet            Started container compute
  Normal  Pulling    14s   kubelet            Pulling image "kubevirt/cirros-container-disk-demo"
  Normal  Pulled     13s   kubelet            Successfully pulled image "kubevirt/cirros-container-disk-demo" in 1.072346472s
  Normal  Created    13s   kubelet            Created container volumecontainerdisk
  Normal  Started    12s   kubelet            Started container volumecontainerdisk
  Normal  Killing    10s   kubelet            Stopping container compute
  Normal  Killing    10s   kubelet            Stopping container volumecontainerdisk
```

- Check logs from compute container:
```
$ kubectl logs -f virt-launcher-testvm-49b46 -c compute
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:68","timestamp":"2021-02-21T05:30:05.814767Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:71","timestamp":"2021-02-21T05:30:05.814825Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu:///system","pos":"libvirt.go:417","timestamp":"2021-02-21T05:30:05.866380Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory')","pos":"libvirt.go:425","timestamp":"2021-02-21T05:30:05.868031Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 6.6.0, package: 13.fc32 (Unknown, 2021-01-21-11:33:00, )","subcomponent":"libvirt","thread":"43","timestamp":"2021-02-21T05:30:05.883000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: testvm","subcomponent":"libvirt","thread":"43","timestamp":"2021-02-21T05:30:05.883000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Child process (dmidecode -q -t 0,1,2,3,4,11,17) unexpected exit status 1: /dev/mem: No such file or directory","pos":"virCommandWait:2741","subcomponent":"libvirt","thread":"43","timestamp":"2021-02-21T05:30:05.883000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:433","timestamp":"2021-02-21T05:30:06.369644Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:432","timestamp":"2021-02-21T05:30:06.374186Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:73","timestamp":"2021-02-21T05:30:06.374474Z"}
{"component":"virt-launcher","level":"info","msg":"Received signal terminated","pos":"virt-launcher.go:437","timestamp":"2021-02-21T05:30:10.286996Z"}
{"component":"virt-launcher","level":"info","msg":"stopping cmd server","pos":"server.go:448","timestamp":"2021-02-21T05:30:10.287245Z"}
{"component":"virt-launcher","level":"info","msg":"cmd server stopped","pos":"server.go:457","timestamp":"2021-02-21T05:30:10.287382Z"}
{"component":"virt-launcher","level":"info","msg":"Exiting...","pos":"virt-launcher.go:466","timestamp":"2021-02-21T05:30:10.287410Z"}
```

**Comment by condaatje** [comment]
also getting `Failed to connect socket to '/var/run/libvirt/libvirt-sock`

https://github.com/kubevirt/kubevirt/issues/3495 didn't help for me but maybe it will for you?

**Comment by pvorontsovd** [comment]
i think key of problem here is
```
{"component":"virt-launcher","level":"info","msg":"Received signal terminated","pos":"virt-launcher.go:437","timestamp":"2021-02-21T05:30:10.286996Z"}
```
i have the same problem with kubevirt version v0.39.0 on k3s
when i install kubevirt version v0.36.1, i also see these info messages,
```
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory')","pos":"libvirt.go:425","timestamp":"2021-02-21T05:30:05.868031Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 6.6.0, package: 13.fc32 (Unknown, 2021-01-21-11:33:00, )","subcomponent":"libvirt","thread":"43","timestamp":"2021-02-21T05:30:05.883000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: testvm","subcomponent":"libvirt","thread":"43","timestamp":"2021-02-21T05:30:05.883000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Child process (dmidecode -q -t 0,1,2,3,4,11,17) unexpected exit status 1: /dev/mem: No such file or directory","pos":"virCommandWait:2741","subcomponent":"libvirt","thread":"43","timestamp":"2021-02-21T05:30:05.883000Z"}
```
but the vm creation is successful

**Comment by wenxinlee2015** [comment]
@Mohitsharma44 the problem has been solved? I meet the same.

**Comment by Mohitsharma44** [comment]
No, I couldn’t get it to work either on microk8s or rke.
-- 
-Thanks
Mohit Sharma
https://sharmamohit.com

**Comment by usrbinkat** [comment]
This is definitely not resolved. I'll be happy to recreate and produce logs also if it would help?

**Comment by wenxinlee2015** [comment]
@Mohitsharma44 @usrbinkat  I have solved this problem because in my scenario, the root path of kubelet was changed to be different from the default path of the community. You can see in the yaml file of daemonset virt-lancher, whether the configuration of kubelet's volume hostpath is the same with your kubelet --root-dir. In addition, some of the code is hard-coded to the default /var/lib/kubelet. if this is the case, it is recommended to change to the default /var/lib/kubelet first

**Comment by usrbinkat** [comment]
Confirmed, as of microk8s 1.21, kubevirt appears to work without issue.

**Comment by t3hmrman** [comment]
Thanks for the tip @wenxinlee2015  -- I just ran into this with [k0s](https://github.com/k0sproject/k0s). That project uses a custom kubelet directory (`/var/lib/k0s/kubelet`) so to fix it I symlinked to get around this:

```console
# ln -s /var/lib/k0s/kubelet /var/lib/kubelet
```

In my case KubeVirt was already installed so I needed to also move the contents of the existing folder @ `/var/lib/kubelet` (minimally, it contains `device_plugins` and an empty `pods` folder) and merge the contents with `/var/lib/k0s/kubelet` (there was no pre-existing `device_plugins` folder but there may be in other setups).

**Comment by echowings** [comment]
The bug still there. Didn't solve with the latest version microk8s and kubevirt
