### ISSUE TITLE
[Conformance][test_id:1780][label:masquerade_binding_connectivity]should allow regular network connection IPv6: Fails external connectivity

### ISSUE THREAD

**Issue by EdDev** [kubevirt/kubevirt#5113]
/kind bug

**What happened**:
IPv6 connectivity check to an external address fails.
The address used is specific to kubevirtci setup (which is a problem by itself).

Filed assertion:
```
By("Checking ping (IPv6) from vmi to cluster nodes gateway")
// Cluster nodes subnet (docker network gateway)
// Docker network subnet cidr definition:
// https://github.com/kubevirt/project-infra/blob/master/github/ci/shared-deployments/files/docker-daemon-mirror.conf#L5
Expect(libnet.PingFromVMConsole(serverVMI, "2001:db8:1::1")).To(Succeed())
```

**What you expected to happen**:
IPv6 connectivity check should pass.

**How to reproduce it (as minimally and precisely as possible)**:
Unable to reproduce it on local run, it seems to happen consistently on CI from the 24/02/2021.

**Anything else we need to know?**:
Job example: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5099/pull-kubevirt-e2e-k8s-cnao-1.19/1365711908715368449

**Comment by enp0s3** [comment]
Checked and it can be reproduced on a local kubevirtci setup, therefore the upstream CI infra is not the root cause

**Comment by EdDev** [comment]
> Checked and it can be reproduced on a local kubevirtci setup, therefore the upstream CI infra is not the root cause

I was not able to reproduce it locally.
I wander what is the difference... I ran it on the CNAO lane.

**Comment by enp0s3** [comment]
@EdDev my bad. I forgot to configure my local docker to support Ipv6, as stated in the [documentation](https://github.com/kubevirt/kubevirtci/blob/b87ef18cd10ed8e98da58c8b0f92620e34407481/cluster-up/cluster/k8s-1.19/README.md#enabling-ipv6-connectivity). Now after the configuration has been applied the tests pass. So indeed it may be related to the [bootstrap](https://github.com/kubevirt/project-infra/pull/835) image change.

**Comment by EdDev** [comment]
This has been confirmed to be related to the prow bootstrap image change.
The bootstrap has been fixed by placing the docker config in the expected location and these tests are now passing fine.

We plan to control the external IP/domain for both IPv4 and IPv6 from outside the tests, in order to allow the checks to occur on clusters that have access to an out-of-cluster IP/domain and to skip it for clusters that do not.

**Comment by phoracek** [comment]
The issue was resolved.

**Comment by oshoval** [comment]
Fails on the new CI node

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1081/rehearsal-pull-kubevirt-e2e-k8s-1.19-sig-network/1379398661657595904

reopen please if desired

```
12:43:02: ------------------------------
12:44:27: S [SKIPPING] [84.937 seconds]
12:44:27: [sig-network] [Serial][rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][level:component]Networking
12:44:27: tests/network/framework.go:27
12:44:27:   VirtualMachineInstance with masquerade binding mechanism
12:44:27:   tests/network/vmi_networking.go:612
12:44:27:     [Conformance][test_id:1780][label:masquerade_binding_connectivity]should allow regular network connection
12:44:27:     tests/network/vmi_networking.go:667
12:44:27:       IPv6
12:44:27:       vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
12:44:27:         with a specific port number [IPv6] [It]
12:44:27:         vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43
12:44:27: 
12:44:27:         [XFAIL] https://github.com/kubevirt/kubevirt/issues/5113, failure: Expected success, but got an error:
12:44:27:             <*errors.errorString | 0xc0012bb8b0>: {
12:44:27:                 s: "Failed to ping VMI testvmi-g5rvh, error: Failed to run [ping -6 2001:db8:1::1 -c 5 -w 10] at VMI testvmi-g5rvh, error: ping -6 2001:db8:1::1 -c 5 -w 10 failed",
12:44:27:             }
12:44:27:             Failed to ping VMI testvmi-g5rvh, error: Failed to run [ping -6 2001:db8:1::1 -c 5 -w 10] at VMI testvmi-g5rvh, error: ping -6 2001:db8:1::1 -c 5 -w 10 failed
12:44:27: 
12:44:27:         tests/network/vmi_networking.go:767
12:44:27: ------------------------------
12:45:54: S [SKIPPING] [86.827 seconds]
12:45:54: [sig-network] [Serial][rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][level:component]Networking
12:45:54: tests/network/framework.go:27
12:45:54:   VirtualMachineInstance with masquerade binding mechanism
12:45:54:   tests/network/vmi_networking.go:612
12:45:54:     [Conformance][test_id:1780][label:masquerade_binding_connectivity]should allow regular network connection
12:45:54:     tests/network/vmi_networking.go:667
12:45:54:       IPv6
12:45:54:       vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
12:45:54:         without a specific port number [IPv6] [It]
12:45:54:         vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43
12:45:54: 
12:45:54:         [XFAIL] https://github.com/kubevirt/kubevirt/issues/5113, failure: Expected success, but got an error:
12:45:54:             <*errors.errorString | 0xc00231a740>: {
12:45:54:                 s: "Failed to ping VMI testvmi-r2glt, error: Failed to run [ping -6 2001:db8:1::1 -c 5 -w 10] at VMI testvmi-r2glt, error: expect: timer expired after 10 seconds",
12:45:54:             }
12:45:54:             Failed to ping VMI testvmi-r2glt, error: Failed to run [ping -6 2001:db8:1::1 -c 5 -w 10] at VMI testvmi-r2glt, error: expect: timer expired after 10 seconds
12:45:54: 
12:45:54:         tests/network/vmi_networking.go:767
12:45:54: ------------------------------
```

**Comment by oshoval** [comment]
@EdDev 
Is it safe to remove the XFAIL from those tests ?
From what i understand this issue is closed
and then we need to fix the failures of it on the new CI cluster (which still doesn't run jobs, and fail this tests mentioned above)

**Comment by EdDev** [comment]
The xfail can be removed once https://github.com/kubevirt/kubevirt/pull/5169 is taken in.

**Comment by oshoval** [comment]
Thanks, and what about the new CI cluster, should https://github.com/kubevirt/kubevirt/pull/5169
take care about it as well, or on other PR ?
test_id 1780 (the one here in this issue title) fails on the new cluster https://github.com/kubevirt/kubevirt/issues/5113#issuecomment-814092722

**Comment by EdDev** [comment]
> Thanks, and what about the new CI cluster, should #5169
> take care about it as well (for example if its the same problem, but since it fails more on the new cluster, it might not be the same), or on other PR ?
> test_id 1780 (the one here in this issue title) fails on the new cluster [#5113 (comment)](https://github.com/kubevirt/kubevirt/issues/5113#issuecomment-814092722)

So you have a new issue on your hand with the same end result.
Being a new cluster smells that something is different there from the "old" cluster.

In any case, I do not think it belongs on this issue.

**Comment by oshoval** [comment]
I will open a new one if needed.
but i don't think we need to parallel investigate when https://github.com/kubevirt/kubevirt/pull/5169 is on going.

**Comment by EdDev** [comment]
> I will open a new one if needed.
> but i don't think we need to parallel investigate when #5169 is on going.

That has nothing to do with it. That PR talks about controlling when to run the test, and you want to discuss why the test fails on a setup where it is expected to pass.
