### ISSUE TITLE
Limit shared mounts to specific VM (launcher) Pods - cleanup needed

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#615]
Because of #613 the VM pod's are no longer trusted. User's need podExec access in order to access the vm's console.

This means all local shared data between VM pods in /var/lib/kubevirt needs to change to a pattern where VM pods can only see data directly pertaining to them.

**Comment by fabiand** [comment]
This one should be fixed after the subresource work, right?

**Comment by davidvossel** [comment]
we still have the situation where sockets are shared between virt-launcher and virt-handler. This is required for communication between the two components. 

However, with the addition of the subresource stream api for console and vnc, there's no reason for a user to need podExec permissions to use KubeVirt.

I'd prefer the VM pod to not need any host shared mounts at some point.

**Comment by fabiand** [comment]
Thanks.

Yes, we still have host mounts, and I agree we should get rid of them. Keeping it open.

**Comment by fabiand** [comment]
@davidvossel is this still a thing?
