### ISSUE TITLE
windows vm gets 169 address

### ISSUE THREAD

**Issue by th-2021** [kubevirt/kubevirt#6448]
When I start the Windows VM kubectl get vmi shortly shows the address in the pod IP range, but a few seconds later it changes to a 169 address.  
(Linux VMs are working)

**Environment**:
- KubeVirt version (use `virtctl version`):
0.45.0
- Kubernetes version (use `kubectl version`):
microk8s 1.22.1

On an older combination this worked.

**Comment by th-2021** [comment]
Networking works through the second interface (multus).

**Comment by salanki** [comment]
Yeah but not primary?

**Comment by th-2021** [comment]
remote desktop is not working on first interface (169). virtctl console works.

**Comment by salanki** [comment]
Inside windows, if you do `ipconfig` does it have an IP on the first interface? If not, if you do `ipconfig /renew` does it get a "The parameter is incorrect" error?

**Comment by th-2021** [comment]
It has the same 169 address. When I try to renew I get a DHCP server error.

**Comment by salanki** [comment]
Ok, I think you are having the same issue we just stumbled upon. Can't get Pod networking to work in any Windows machine in recent Kubevirt builds. I am working on tracking down the commit where the issue was introduced, I will keep you posted.

**Comment by salanki** [comment]
Ok, we found the issue, see #6462. If you want to get this working now, you can use our fixed branch. Change your virt-operator deployment to reference image: `registry.gitlab.com/atlantic-crypto/kubevirt/virt-operator:cw-network9`

**Comment by maiqueb** [comment]
Would you retry w/ latest master ? There's a good chance this was fixed by https://github.com/kubevirt/kubevirt/pull/6465.

**Comment by th-2021** [comment]
I just tried against main, but the issue is still there.
To test it did:
kubectl apply -f _out/manifests/release/kubevirt-operator.yaml
kubectl apply -f _out/manifests/release/kubevirt-cr.yaml
<wait until all pods are ready again>
kubectl delete -f win10.yaml
kubectl create -f win10.yaml

was this right?

**Comment by th-2021** [comment]
after 2 hours (next time I looked at it) the pod address was shown and no longer the 169 address.
